export const universities = [
    "University of Dhaka (DU)",
    "Bangladesh University of Engineering and Technology (BUET)",
    "Jahangirnagar University (JU)",
    "Rajshahi University (RU)",
    "Chittagong University (CU)",
    "Shahjalal University of Science and Technology (SUST)",
    "Khulna University of Engineering & Technology (KUET)",
    "Rajshahi University of Engineering & Technology (RUET)",
    "Chittagong University of Engineering & Technology (CUET)",
    "Bangladesh University of Textiles (BUTEX)",
    "Bangladesh University of Professionals (BUP)",
    "Jagannath University (JnU)",
    "Bangabandhu Sheikh Mujibur Rahman Maritime University (BSMRMU)",
    "IUT (Islamic University of Technology)",
    "North South University (NSU)",
    "BRAC University",
    "East West University (EWU)",
    "Independent University, Bangladesh (IUB)",
    "American International University-Bangladesh (AIUB)",
    "United International University (UIU)",
    "Ahsanullah University of Science and Technology (AUST)",
    "Daffodil International University (DIU)",
    "University of Liberal Arts Bangladesh (ULAB)",
    "Green University of Bangladesh",
    "International Islamic University Chittagong (IIUC)",
    "Khulna University (KU)",
    "Sher-e-Bangla Agricultural University (SAU)",
    "Noakhali Science and Technology University (NSTU)",
    "Comilla University (CoU)",
    "Barisal University (BU)",
    "Stamford University Bangladesh",
    "State University of Bangladesh",
    "Eastern University",
    "Metropolitan University",
    "Leading University",
    "Notre Dame University Bangladesh",
    "Canadian University of Bangladesh",
    "Presidency University",
    "Primeasia University",
    "Southeast University (SEU)",
    "Manarat International University",
    "City University",
    "World University of Bangladesh",
    "Northern University Bangladesh",
    "Uttara University",
    "Asian University of Bangladesh",
    "Harvard University",
    "Stanford University",
    "MIT",
    "University of Oxford",
    "University of Cambridge",
    "Cornell University",
    "Yale University",
    "Princeton University",
    "Columbia University",
    "University of Pennsylvania",
    "National University of Singapore",
    "Tsinghua University",
    "Peking University",
    "The University of Tokyo"
];
